#!/usr/bin/php
<?php 
/*
 * Copyright (C) 2013-2014 RuneAudio Team
 * http://www.runeaudio.com
 *
 * RuneUI
 * copyright (C) 2013-2014 - Andrea Coiutti (aka ACX) & Simone De Gregori (aka Orion)
 *
 * RuneOS
 * copyright (C) 2013-2014 - Carmelo San Giovanni (aka Um3ggh1U) & Simone De Gregori (aka Orion)
 *
 * RuneAudio website and logo
 * copyright (C) 2013-2014 - ACX webdesign (Andrea Coiutti)
 *
 * This Program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * This Program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with RuneAudio; see the file COPYING.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.txt>.
 *
 *  file: command/refresh_nics
 *  version: 1.3
 *
 */

// common include
ini_set('display_errors', '1');
// ini_set('error_reporting', -1);
ini_set('error_log','/var/log/runeaudio/refresh_nics.log');
// Connect to Redis backend
$redis = new Redis();
$redis->connect('127.0.0.1', 6379);
include('/var/www/app/libs/runeaudio.php');
include '/var/www/app/libs/vendor/ziegler/iwlist-parser.class.php';
// refesh visible wifi networks.
$iw = new iwlist_parser;
// debug
// print_r($iw->parseScanDev( 'wlan0' ));
wrk_netconfig($redis,'setnics');
$nics = wrk_netconfig($redis,'getnics');
// debug
// print_r($nics);
foreach ($nics as $key => $nicdetail) {
	if ($nicdetail->wireless === 1) {
		// temp
		$scan = $iw->parseScanDev( $key );
		$redis->set('wlans',json_encode($scan));
		
		// debug
		// print_r($scan);
		foreach ($scan as $nicname => $nicscan) {
			foreach ($nicscan as $count => $wlan) {
				foreach ($wlan as $key => $value) {
					$wlans[$count]['nic'] = $nicname;
					if ($key === 'ESSID') {
						$wlans[$count][$key] = $value;
						if ($nicdetail->currentssid === $key) { $wlans[$count]['connected'] = 1; } else { $wlans[$count]['connected'] = 0; }
					}
					if ($key === 'Encryption key') $wlans[$count]['encryption'] = $value;
				}
			}
		} 
		// debug
		// print_r($wlans);
		// render wlans channel
		ui_render('wlans',json_encode($wlans));
	}
}

